CC=g++

INCLUDE_DIR=../include
BRIDGES_INC=$(INCLUDE_DIR)/bridges-cxx/src
RAPIDJSON_INC=$(INCLUDE_DIR)/rapidjson/include/

CXXFLAGS = -std=c++14 -g -I $(BRIDGES_INC) -I $(BRIDGES_INC)/data_src -I $(RAPIDJSON_INC) -lcurl

all: proj

main:

clean:
	-rm proj
